word_list = [
    "cars",
    "computer",
    "python",
    "hangman",
    "programming",
    "game",
    "learning",
    "fun",
    "Tenacious",
    "Serendipity",
    "Mellifluous",
    "Quixotic",
    "Luminous",
    "Pensive",
    "Solitude",
    "Ethereal",
    "Serene",
    "Resilient",
    "Jubilant",
    "Voracious",
    "aberration", "bellicose", "capitulate", "debilitate", "elucidate",
    "facetious", "gregarious", "hapless", "iconoclast", "juxtapose",
    "kaleidoscope", "laconic", "magnanimous", "nefarious", "obfuscate",
    "paradigm", "recapitulate", "sagacious", "tantamount",
    "ubiquitous", "vacuous", "wanton", "xenophobia", "yoke",
    "zealous", "abdicate", "benevolent", "cacophony", "dichotomy"
    ]

word_definitions = {
    "cars": "Plural form of car; motor vehicles with four wheels, powered by an internal combustion engine or electric motor, designed to carry a small number of passengers.",
    "computer": "An electronic device for storing and processing data, typically in binary form, according to instructions given to it in a variable program.",
    "python": "A large, heavy-bodied snake that is nonvenomous and native to tropical and subtropical regions, or a high-level programming language known for its readability and versatility.",
    "hangman": "A game in which one player tries to guess the letters of a word chosen by another player, with incorrect guesses resulting in parts of a stick figure being drawn to represent a hanging man.",
    "programming": "The process of writing, testing, and maintaining code in a computer language to create software, applications, and systems.",
    "game": "An activity or sport usually involving skill, knowledge, or chance, in which you follow fixed rules and try to win against an opponent or solve a puzzle.",
    "learning": "The acquisition of knowledge or skills through study, experience, or teaching.",
    "fun": "Enjoyment, amusement, or light-hearted pleasure.",
    "tenacious": "Tending to keep a firm hold of something; clinging or adhering closely; persistent and determined.",
    "serendipity": "The occurrence and development of events by chance in a happy or beneficial way.",
    "mellifluous": "Sweet or musical; pleasant to hear.",
    "luminous": "Emitting or reflecting light, glowing; illuminating.",
    "pensive": "Engaged in, involving, or reflecting deep or serious thought.",
    "solitude": "The state or situation of being alone, often by choice and usually with a sense of peace and quiet.",
    "ethereal": "Extremely delicate and light in a way that seems too perfect for this world; heavenly or spiritual.",
    "serene": "Calm, peaceful, and untroubled; tranquil.",
    "resilient": "Able to withstand or recover quickly from difficult conditions; flexible and durable.",
    "jubilant": "Feeling or expressing great happiness and triumph.",
    "voracious": "Wanting or devouring great quantities of food; having a very eager approach to an activity.",
    "aberration": "A departure from what is normal, usual, or expected, typically an unwelcome one.",
    "bellicose": "Demonstrating aggression and willingness to fight.",
    "capitulate": "Cease to resist an opponent or an unwelcome demand; surrender.",
    "debilitate": "Make (someone) weak and infirm.",
    "elucidate": "Make (something) clear; explain.",
    "facetious": "Treating serious issues with deliberately inappropriate humor; flippant.",
    "gregarious": "Fond of company; sociable.",
    "hapless": "Unfortunate.",
    "iconoclast": "A person who attacks or criticizes cherished beliefs or institutions.",
    "juxtapose": "Place or deal with close together for contrasting effect.",
    "kaleidoscope": "A constantly changing pattern or sequence of elements.",
    "laconic": "Using very few words.",
    "magnanimous": "Generous or forgiving, especially towards a rival or less powerful person.",
    "nefarious": "Wicked or criminal.",
    "obfuscate": "Render obscure, unclear, or unintelligible.",
    "paradigm": "A typical example or pattern of something; a model.",
    "quixotic": "Exceedingly idealistic; unrealistic and impractical.",
    "recapitulate": "Summarize and state again the main points of.",
    "sagacious": "Having or showing keen mental discernment and good judgment; wise or shrewd.",
    "tantamount": "Equivalent in seriousness to; virtually the same as.",
    "ubiquitous": "Present, appearing, or found everywhere.",
    "vacuous": "Having or showing a lack of thought or intelligence; mindless.",
    "wanton": "Deliberate and unprovoked (often referring to cruel or violent actions).",
    "xenophobia": "Dislike of or prejudice against people from other countries.",
    "yoke": "A wooden crosspiece fastened over the necks of two animals and attached to the plow or cart they are to pull.",
    "zealous": "Having or showing great energy or enthusiasm in pursuit of a cause or objective.",
    "abdicate": "Renounce one's throne.",
    "benevolent": "Well meaning and kindly.",
    "cacophony": "A harsh, discordant mixture of sounds.",
    "dichotomy": "A division or contrast between two things that are or are represented as being opposed or entirely different."}

